# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESP32_Websocket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Starscream', '~> 2.1'

  # Pods for ESP32_Websocket

  target 'ESP32_WebsocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ESP32_WebsocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
